Add doc to setup tmux
ludoboulanger/cyclee-app pull request #25
Opened 2022-02-05 23:32 UTC by AntoineLaberge

Add the docs to setup tmux on Mac and Windows (using WSL).

2022-02-06 01:32 UTC, VicoF requested changes

2022-02-06 01:32 UTC, VicoF commented on README.md
> +| Victor  | Dev - Junior 👶 | Database superstar |
hahahha

2022-02-06 01:32 UTC, VicoF commented on docs/tmuxinator-setup.md
> +# ~/.tmuxinator/cyclee.yml
pourquoi tu commit pas ce fichier là?

2022-02-06 01:32 UTC, VicoF commented on docs/tmuxinator-setup.md
> +        - docker compose up hasura-console
juste docker-compose up -d je pense

2022-02-06 01:32 UTC, VicoF commented on docs/tmuxinator-setup.md
> +        - docker compose up hasura-console
Manquerait aussi `cd database`

2022-02-06 15:49 UTC, AntoineLaberge commented on docs/tmuxinator-setup.md
> +# ~/.tmuxinator/cyclee.yml
Il est commit non?

2022-02-06 15:51 UTC, AntoineLaberge commented on docs/tmuxinator-setup.md
> +        - docker compose up hasura-console
Oui! J'avais pas encore update ça, j'aurais du le mettre en draft

2022-02-06 16:26 UTC, AntoineLaberge commented on docs/tmuxinator-setup.md
> +
Le lien dans la section Windows au point 1 explique comment faire. Ce sont les mêmes steps pour WSL1 ou 2!

2022-02-20 20:37 UTC, VicoF approved these changes

2022-02-20 20:37 UTC, merged