Signup flow front end
ludoboulanger/cyclee-app pull request #38
Opened 2022-03-18 03:22 UTC by VicoF

Loin d'être parfait mais c'est un bon début je crois!

![image](https://user-images.githubusercontent.com/44242537/158931415-85d9c568-c9d6-49fc-9f7e-93d041435afe.png)

![image](https://user-images.githubusercontent.com/44242537/158931405-e2eda830-7c16-4c3f-a184-87d4ae501af1.png)

2022-03-27 13:43 UTC, AntoineLaberge requested changes

2022-04-23 17:40 UTC, VicoF commented on frontend/components/TextField/index.tsx
> +const StyledField = styled("input")({
Celui là se veut vraiment être un component, c'était simplement pour avoir un input avec un style commun qu'on va pouvoir réutiliser un peu partout

2022-04-23 17:56 UTC, VicoF commented on frontend/public/locales/en/signup.json
> +{
j'ai ajouté le formfields, mais j'ai gardé la structure d'avant parce que il uarait fallu que je le change à trop de places haha

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/components/FormField/index.tsx
> +import { Typography } from "@mui/material";
J'ai fait une autre composante form-field pour react-hook-form seulement! On checkera laquelle on veut utiliser

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/components/SignupForm/PasswordPage.tsx
> +    console.log(form.formState.errors);
À quoi sert ce console.log là?

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/components/TextField/index.tsx
> +const StyledField = styled("input")({
Good!

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/pages/signup/index.tsx
> +    console.log(data);
On veut garder ce console.log là?

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/public/locales/en/signup.json
> +{
C'est bon! ahahahh

2022-04-25 21:55 UTC, AntoineLaberge commented on frontend/components/SignupForm/ConfirmationPage.tsx
> +  paddingTop: "50px",
Pour le padding tu peux l'écrire en une ligne : 
`padding: "50px 70px",`

2022-04-26 13:48 UTC, VicoF commented on frontend/components/SignupForm/PasswordPage.tsx
> +    console.log(form.formState.errors);
arjyen, petit oubli

2022-04-27 16:43 UTC, AntoineLaberge approved these changes

2022-04-27 18:00 UTC, merged