Add navigation bars for desktop and mobile
ludoboulanger/cyclee-app pull request #40
Opened 2022-03-21 13:31 UTC by AntoineLaberge

Add empty navigation bar for desktop and mobile!

Issue: #39

2022-03-26 19:20 UTC, VicoF requested changes

2022-03-26 19:20 UTC, VicoF commented on frontend/components/navigation-bar/navigation-bar.tsx
> +                    <StyledRightContent mobile={isMobile.toString()}>
pourquoi pas isMobile.toString() et pas plutôt un bool direct?

2022-03-26 19:20 UTC, VicoF commented on frontend/components/navigation-tabs/navigation-tabs.tsx
> +    const [value, setValue] = useState(0);
value est un peu générique comme nom, peut être plutôt tabIndex ou de quoi du genre?

2022-03-26 19:20 UTC, VicoF commented on frontend/components/responsive-viewport/default.tsx
> +  const isNotMobile = useMediaQuery(`(min-width:${MIN_WIDTH}px)`);
Personnellement je mettrais plutôt isMobile, ça fait une double négation avec l'opérateur ternaire sinon et ça se lit moins bien

2022-03-26 19:20 UTC, VicoF commented on frontend/components/responsive-viewport/mobile.tsx
> +  const isMobile = useMediaQuery(`(max-width:${MAX_WIDTH}px)`);
Pour éviter de dupliquer du code tu pourrais utilise useIsMobile ici

2022-03-26 19:20 UTC, VicoF commented on frontend/components/responsive-viewport/desktop.tsx
> +  const isDesktop = useMediaQuery(`(min-width:${MIN_WIDTH}px)`);
voir commentaire précédent

2022-03-26 19:20 UTC, VicoF commented on frontend/components/responsive-viewport/default.tsx
> +  const isNotMobile = useMediaQuery(`(min-width:${MIN_WIDTH}px)`);
En fait tu pourrais utiliser le useIsMobile ici

2022-03-26 19:20 UTC, VicoF commented on frontend/components/responsive-viewport/default.tsx
> +
Au final je me question sur les hooks, on devrait peut-être utiliser directement les breakpoints du theme non? https://mui.com/system/basics/#custom-breakpoints

2022-03-26 19:20 UTC, VicoF commented on frontend/next.config.js
> +    return config;
c'est pour quoi ça?

2022-03-26 19:20 UTC, VicoF commented on frontend/components/search-bar/search-bar.tsx
> +            {!minimalSearchBar ?
Encore une fois je trouve que ça crée de la confusion le `!`, je l'enleverais et inverserait les deux outputs

2022-03-26 19:20 UTC, VicoF commented on frontend/pages/_app.tsx
> +        {isMobile && <BottomNavigationBar />}
Tu pourrais utiliser le component 
```js
<Mobile> <BottomNavigationBar /> <Mobile/> 
```
Que t'as fais à la place

2022-04-01 18:12 UTC, AntoineLaberge commented on frontend/components/navigation-bar/navigation-bar.tsx
> +                    <StyledRightContent mobile={isMobile.toString()}>
Le styled component de MUI accepte des fois des boolean ou non. À investiguer!

2022-04-01 18:14 UTC, AntoineLaberge commented on frontend/components/navigation-tabs/navigation-tabs.tsx
> +    const [value, setValue] = useState(0);
True, j'ai oublié de le changer!

2022-04-01 18:22 UTC, AntoineLaberge commented on frontend/components/responsive-viewport/default.tsx
> +
Ces hooks peuvent être utilisé ailleurs que sur des composantes MUI. On pourrait à la limite set les mêmes valeurs dans le theme de MUI si jamais on doit s'en servir un jour?

2022-04-01 18:26 UTC, AntoineLaberge commented on frontend/pages/_app.tsx
> +        {isMobile && <BottomNavigationBar />}
Bonne idée!

2022-04-16 23:43 UTC, VicoF approved these changes
Good job!

2022-04-23 16:19 UTC, merged